// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyeWCOqB4UUY9il4oLjCck9jqBJWCLayM',
    appId: '1:201529751912:web:ae64358f39b92c6aa97edd',
    messagingSenderId: '201529751912',
    projectId: 'crudtutorial-9e145',
    authDomain: 'crudtutorial-9e145.firebaseapp.com',
    storageBucket: 'crudtutorial-9e145.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJkSJh-LvSiEtp3iUgKidBcaeneVecpw',
    appId: '1:201529751912:android:db7f2f1e64e2fa97a97edd',
    messagingSenderId: '201529751912',
    projectId: 'crudtutorial-9e145',
    storageBucket: 'crudtutorial-9e145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2MhYBxrxn5e6gHydDvsCUgKxoN4R6q2I',
    appId: '1:201529751912:ios:5ddecc9ca34f2b38a97edd',
    messagingSenderId: '201529751912',
    projectId: 'crudtutorial-9e145',
    storageBucket: 'crudtutorial-9e145.firebasestorage.app',
    iosBundleId: 'com.example.crudMasterclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2MhYBxrxn5e6gHydDvsCUgKxoN4R6q2I',
    appId: '1:201529751912:ios:5ddecc9ca34f2b38a97edd',
    messagingSenderId: '201529751912',
    projectId: 'crudtutorial-9e145',
    storageBucket: 'crudtutorial-9e145.firebasestorage.app',
    iosBundleId: 'com.example.crudMasterclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyeWCOqB4UUY9il4oLjCck9jqBJWCLayM',
    appId: '1:201529751912:web:4062c4d1993afb40a97edd',
    messagingSenderId: '201529751912',
    projectId: 'crudtutorial-9e145',
    authDomain: 'crudtutorial-9e145.firebaseapp.com',
    storageBucket: 'crudtutorial-9e145.firebasestorage.app',
  );
}
